### ISSUE TITLE
Instant Crash on Load

### ISSUE THREAD

**Issue by Sikksens** [wakjah/SpaceEngineersBadRefining#1]
Seems to crash any save game instantly due to missing blueprint

```2024-03-11 11:13:30.431 - Thread:   1 ->  No blueprint with Id 'MyObjectBuilder_BlueprintDefinition/StoneOreToIngotBasic'
2024-03-11 11:13:30.432 - Thread:   1 ->  [BadRefining]: ERROR: Blueprint not found: StoneOreToIngotBasic
2024-03-11 11:13:30.432 - Thread:   1 ->  Error: Error during loading session:System.NullReferenceException: Object reference not set to an instance of an object.
   at BadRefiningMod.Session.MultiplyBlueprintResultAmounts(MyBlueprintDefinitionBase blueprint, Single factor)
   at BadRefiningMod.Session.LoadData()
   at Sandbox.Game.World.MySession.LoadComponent(MySessionComponentBase component)
   at Sandbox.Game.World.MySession.LoadDataComponents()
   at Sandbox.Game.World.MySession.PrepareBaseSession(MyObjectBuilder_Checkpoint checkpoint, MyObjectBuilder_Sector sector)
   at Sandbox.Game.World.MySession.Load(String sessionPath, MyObjectBuilder_Checkpoint checkpoint, UInt64 checkpointSizeInBytes, Boolean saveLastStates, Boolean allowXml)```

**Comment by elkx1** [comment]
Thanks for the report!

I have now fixed this on master and published an updated version on the mod portal.
